# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b58a8d54c2d88aa44440440a72c833abb0d4df26a690442675d9c6c49a508b3a5ed40e5e36e072c5e9dd2d04ad560b9be4e8bb22bd28c576d1547808e42c047

test:
  secret_key_base: f53ef6af0311a3890547f25ead02252f19bfb2aa0d81f44afa2922a64b7a96afc98ca2e9954bc1140d9eb874e32f7dbd7ce37e9b8fdd2872c0f34e8484f38f20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
